on:
  release:
    types: [published, updated]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/running-release-tags-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          update-full-release: true
        if: github.event.release.prerelease == false
